export type Workspace = {
    name: string
    version: string
  }

export enum CompoundClass {
  anaesthetic = 'anaesthetic',
  analgesic = 'analgesic',
  anticonvulsant = 'anti-convulsant',
  anticepressant = 'anti-depressant',
  antihistamine = 'antihistamine',
  antimicrobial = 'antimicrobial',
  antiparasitic = 'antiparasitic',
  barbiturate = 'barbiturate',
  benzodiazepine = 'benzodiazepine',
  cannabinoid = 'cannabinoid',
  cathinone = 'cathinone',
  cocainebyproducts = 'cocaine byproducts',
  depressant = 'depressant',
  designerbenzodiazepine = 'designer benzodiazepine',
  dietarysupplement = 'dietary supplement',
  dissociativeanesthetic = 'dissociative anesthetic',
  fentanylbyproducts = 'fentanyl byproducts',
  hallucinogen = 'hallucinogen',
  heroinbyproducts = 'heroin byproducts',
  musclerelaxant = 'muscle relaxant',
  naturalalkaloid = 'natural alkaloid',
  opiateopioid = 'opiate/opioid',
  parafluorofentanylbyproducts = 'para-fluorofentanyl byproducts',
  psychadelic = 'psychadelic',
  steroid = 'steroid',
  stimulant = 'stimulant',
  substitutedcathinone = 'substituted cathinone',
  sugar = 'sugar',
  syntheticcannabinoid = 'synthetic cannabinoid',
}

export enum SubstanceCommonRole {
  ActiveIngredient = 'active ingredient',
  Cut = 'cut',
  Metabolite = 'metabolite',
  Precursor = 'precursor',
  SynthesisByProduct = 'synthesis-by-product',
}

export enum SampleType {
  Cotton = 'cotton',
  Pill = 'pill',
  Spatula = 'spatula',
  Swab = 'swab',
  Syringe = 'syringe',
  Other = 'other',
  Unknown = 'unknown',
}

export enum SampleTextures {
  Capsule = 'capsule',
  Chalky = 'chalky',
  Chunky = 'chunky',
  Clay = 'clay',
  Clumpy = 'clumpy',
  Crumbly = 'crumbly',
  Crystals = 'crystals',
  Dull = 'dull',
  Edibles = 'edibles',
  FakePill = 'fake pill',
  Flaky = 'flaky',
  Grainy = 'grainy',
  Granular = 'granular',
  Gummy = 'gummy',
  Hard = 'hard',
  Liquid = 'liquid',
  Mushrooms = 'mushrooms',
  NotSpecified = 'not specified',
  OilWax = 'oil/wax',
  Other = 'other',
  Paper = 'paper',
  PaperBlotter = 'paper blotter',
  Paste = 'paste',
  Pill = 'pill',
  PlantLeaf = 'plant/leaf',
  Plastic = 'plastic',
  Powder = 'powder',
  Rock = 'rock',
  Rubbery = 'rubbery',
  Scaly = 'scaly',
  Shiny = 'shiny',
  Soft = 'soft',
  Solid = 'solid',
  Spots = 'spots',
  Stamp = 'stamp',
  Sticky = 'sticky',
  Tar = 'tar',
  Waxy = 'waxy',
  Wet = 'wet',
}

export enum SampleColors {
  Amber = 'amber',
  Beige = 'beige',
  Black = 'black',
  BlackSpecks = 'black specks',
  Blue = 'blue',
  Brown = 'brown',
  Clear = 'clear',
  Cloudy = 'cloudy',
  Colorless = 'colorless',
  DarkBlue = 'dark blue',
  DarkBrown = 'dark brown',
  DarkGray = 'dark gray',
  DarkGreen = 'dark green',
  DarkerWhite = 'darker white',
  Gray = 'gray',
  GrayWhite = 'gray-white',
  Green = 'green',
  LightBeige = 'light beige',
  LightBlue = 'light blue',
  LightBrown = 'light brown',
  LightGray = 'light gray',
  LightGreen = 'light green',
  LightOrange = 'light orange',
  LightPink = 'light pink',
  LightPurple = 'light purple',
  LightRed = 'light red',
  LightTan = 'light tan',
  LightYellow = 'light yellow',
  MultiColored = 'multi-colored',
  NavyBlue = 'navy blue',
  NotSpecified = 'not specified',
  OffWhite = 'off-white',
  Opaque = 'opaque',
  Orange = 'orange',
  Peach = 'peach',
  Pink = 'pink',
  Purple = 'purple',
  Red = 'red',
  Speckled = 'speckled',
  Tan = 'tan',
  Unknown = 'unknown',
  White = 'white',
  Yellow = 'yellow',
}

export enum SampleSensations {
  Burning = 'burning',
  Dizzy = 'dizzy',
  Good = 'good',
  Hallucinations = 'hallucinations',
  Jittery = 'jittery',
  Long = 'long',
  Meh = 'meh',
  Mellow = 'mellow',
  Mixed = 'mixed',
  MoreDown = 'more down',
  MoreUp = 'more up',
  Nausea = 'nausea',
  Nice = 'nice',
  Normal = 'normal',
  NotSpecified = 'not specified',
  Other = 'other',
  Sedating = 'sedating',
  SeizureLike = 'seizure/seizure-like',
  Sleepy = 'sleepy',
  Stronger = 'stronger',
  Typical = 'typical',
  Unknown = 'unknown',
  Unpleasant = 'unpleasant',
  UnusualTaste = 'unusual taste',
  Vomitting = 'vomitting',
  Weaker = 'weaker',
  Weird = 'weird'
}

export enum OverdoseStatus {
  Unknown, 
  Involved, 
  NonOd = "not overdose related"
}

export enum AnalysisMethod {
  GCMS, 
  FTIR, 
  DGCMS = "Derivatized GCMS",
}

export enum AbundanceLevels {
  None, 
  Trace, 
  IndicationOf = 'indication of',
}

export enum LabAnalysisStatus {
  Pending, 
  Complete, 
  FurtherInvestigation = 'pending further investigation',
}

export enum ExpectedSubstance {
  TwoCB = '2C-B',
  ThreeMeoPcp = '3-MeO-PCP',
  FourMM = '4MM',
  FourMmc = '4-MMC',
  FiveMeoDmt = '5-MeO-DMT',
  SixApb = '6-APB',
  Amphetamine = 'amphetamine',
  Benzodiazepine = 'benzodiazepine',
  Buprenorphine = 'buprenorphine',
  Caffeine = 'caffeine',
  Carfentanil = 'carfentanil',
  Carisoprodol = 'carisoprodol',
  Cathinone = 'cathinone (bath salts)',
  Cbd = 'CBD',
  Cocaine = 'cocaine',
  Codeine = 'codeine',
  Crack = 'crack',
  Delta9Thc = 'Delta-9-THC',
  Dmt = 'DMT',
  Ecstasy = 'ecstasy',
  Fentanyl = 'fentanyl',
  Fluorexetamine = 'fluorexetamine (FXE)',
  Gabapentin = 'gabapentin',
  Ghb = 'GHB',
  Heroin = 'heroin',
  Hydrocodone = 'hydrocodone',
  Inositol = 'inositol',
  Ketamine = 'ketamine',
  Lsd = 'LSD',
  M30 = 'M30',
  Mda = 'MDA',
  Mdma = 'MDMA',
  Mephedrone = 'mephedrone',
  Mescaline = 'mescaline',
  Methadone = 'methadone',
  Methamphetamine = 'methamphetamine',
  Methylfentanyl = 'methylfentanyl',
  Molly = 'molly',
  Nitazene = 'nitazene',
  Oxycodone = 'oxycodone',
  Parexyl = 'parexyl',
  Percocet = 'Percocet',
  Psilocybin = 'psilocybin',
  Steroids = 'steroids',
  SyntheticCannabis = 'synthetic cannabis',
  Tapentadol = 'tapentadol',
  Testosterone = 'testosterone',
  Tramadol = 'tramadol',
  Unknown = 'unknown',
  Weed = 'weed',
  Xanax = 'Xanax',
  Xylazine = 'xylazine',
}

export enum KitStatus {
  WithContact, 
  Received,
  Lost,
  Defective
}